import { Inter } from "next/font/google";
import { ToastContainer } from "react-toastify";
import Header from "./components/Header/Header";

export const metadata = {
  title: "Next.js",
  description: "Generated by Next.js",
};

const inter = Inter({ subsets: ["latin"] });

export default function RootLayout({ children }) {
  return (
    <html lang="uk">
      <head></head>
      <body className={inter.className}>
        <header>
          <Header />
        </header>
        <main>{children}</main>
        <ToastContainer />
      </body>
    </html>
  );
}
